[package]
name = "dns-rust"
version = "0.1.0"
authors = ["Jie Yang <jie.yang@nanchao.org>"]
edition = "2018"

[dependencies]
c-ares = "7.1"
futures = "0.1"
mio-extras = "2.0.4"
mio = "0.6"
tokio = "0.1"
c-ares-resolver = "6.1.0"
yaml-rust = "0.4"
